### ISSUE TITLE
Upgrade the fuse explorer to the latest version

### ISSUE THREAD

**Issue by leonprou** [fuseio/blockscout#4]
At fuse.io we are turning communities into thriving economies
Allowing companies and communities to enable secure and
friction-less mobile payments with ease.
# Project scope
Blockscout is the block explorer of our network. It is available on https://explorer.fuse.io/. We are using a fork of the v1 version of the explorer, while the latest version is v3. We seek to update our fork version to the latest one avaiable. All code is open sourced here https://github.com/fuseio/blockscout. 
## Requirements
Rebase our fork with the latest (v3) blockscout version, bringing all the changes to the forked version. The changes include:
- our customizations of UI (css) and texts, links, etc
- The live dashboard on top of the explorer
bonus point: setup a synced version of the explorer on a given EC2 instance.
## Resources 
- [explorer live](https://explorer.fuse.io/)
- [our fork repo](https://github.com/fuseio/blockscout)
- [blockscout repo](https://github.com/poanetwork/blockscout)

# Definition of Done
- PR on our repo with the changes that fulfil the requirements
- a demonstration that the PR fulfils the requirements.

**Comment by leonprou** [comment]
@mul53 you can start working on this.
Tell if you need anything from our side.

**Comment by mul53** [comment]
@leonprou on it

**Comment by leonprou** [comment]
@mul53 great! can you give me your email or telegram handle? send me on leon@fuse.io
